name: Publish Release

on:
  push:
    branches: [ master ]
    tags: 
      - "*"

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish artifacts
      env:
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}   
      run: ./gradlew uploadArchives --no-daemon --no-parallel
